// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'keys.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: webApiKey,
    appId: '1:992891578087:web:1a76376593137d3f2d2442',
    messagingSenderId: '992891578087',
    projectId: 'collevo-edu',
    authDomain: 'collevo-edu.firebaseapp.com',
    storageBucket: 'collevo-edu.appspot.com',
    measurementId: 'G-LT1S9NNBHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: androidApiKey,
    appId: '1:992891578087:android:643d9baa11d2cff32d2442',
    messagingSenderId: '992891578087',
    projectId: 'collevo-edu',
    storageBucket: 'collevo-edu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: iosApiKey,
    appId: '1:992891578087:ios:c78a88cd52804d072d2442',
    messagingSenderId: '992891578087',
    projectId: 'collevo-edu',
    storageBucket: 'collevo-edu.appspot.com',
    iosClientId: '992891578087-7u4b9ij6kuit9mo40ncuvksr42laomp2.apps.googleusercontent.com',
    iosBundleId: 'com.benstech.collevoStudent',
  );
}
